FROM node:16.8.0

WORKDIR /app

ARG PORT
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG JWT_SECRET
ARG SCOPES
ARG REDIRECT_URI
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG EMAIL_SERVER
ARG COMMAND

ENV PORT                   8080
ENV CLIENT_ID              ${CLIENT_ID}
ENV CLIENT_SECRET          ${CLIENT_SECRET}
ENV JWT_SECRET             ${JWT_SECRET}
ENV SCOPES                 ${SCOPES}
ENV REDIRECT_URI           ${REDIRECT_URI}
ENV AWS_ACCESS_KEY_ID      ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY  ${AWS_SECRET_ACCESS_KEY}
ENV EMAIL_SERVER           ${EMAIL_SERVER}
ENV COMMAND                ${COMMAND}

COPY . .

RUN npm ci

EXPOSE 8080

CMD sh -c "npm run ${COMMAND}"