name: Deploy Backend

on:
    push:
      branches:
        - main

env:
  GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
  ACCOUNT_ID:          ${{ secrets.ACCOUNT_ID }} 
  ACCESS_KEY:          ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_NAME:            ${{ secrets.ECR_NAME }}
  AWS_REGION:          ${{ secrets.AWS_REGION }} 
  PROJECT_ID:          ${{ secrets.PROJECT_ID }}
  BACKEND_SERVICE:     ${{ secrets.BACKEND_SERVICE }}
  ARTIFACT_REGISTRY:   ${{ secrets.ARTIFACT_REGISTRY }}  


jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:latest
          service: ${{ env.BACKEND_SERVICE }}
          region: us-central1
          platform: managed
          allow-unauthenticated: true