name: Deploy Frontend

on:
  push:
    branches:
      - main

env:
  GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
  ACCOUNT_ID:          ${{ secrets.ACCOUNT_ID }} 
  ACCESS_KEY:          ${{secrets.AWS_ACCESS_KEY_ID}}
  SECRET_ACCESS_KEY:   ${{secrets.AWS_SECRET_ACCESS_KEY}}
  ECR_NAME:            ${{secrets.ECR_NAME}}
  AWS_REGION:          ${{ secrets.AWS_REGION }} 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Build Frontend Application
      id: build-frontend
      run: |
            cd front-end
            npm i
            npm run build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./front-end/dist/ s3://appliscan-frontend --delete

      