name: Deploy Email API

on:
    push:
      branches:
        - main
        - gmail-api

env:
  GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
  ACCOUNT_ID:          ${{ secrets.ACCOUNT_ID }} 
  ACCESS_KEY:          ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_NAME:            ${{ secrets.ECR_NAME }}
  AWS_REGION:          ${{ secrets.AWS_REGION }} 
  PROJECT_ID:          ${{ secrets.PROJECT_ID }}
  BACKEND_SERVICE:     ${{ secrets.BACKEND_SERVICE }}
  ARTIFACT_REGISTRY:   ${{ secrets.ARTIFACT_REGISTRY }}  
  CLIENT_ID:           ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET:       ${{ secrets.CLIENT_SECRET }}
  JWT_SECRET:          ${{ secrets.JWT_SECRET }}
  SCOPES:              ${{ secrets.SCOPES }}
  REDIRECT_URI:        ${{ secrets.REDIRECT_URI }}
  EMAIL_SERVICE:       ${{ secrets.EMAIL_SERVICE }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/appliscan-gmail-api/${{ env.EMAIL_SERVICE }}:latest
          build-args: |
            CLIENT_ID=${{env.CLIENT_ID}}
            CLIENT_SECRET=${{env.CLIENT_SECRET}}
            JWT_SECRET=${{env.JWT_SECRET}}
            SCOPES=${{env.SCOPES}}
            REDIRECT_URI=${{env.REDIRECT_URI}}
            AWS_ACCESS_KEY_ID=${{env.ACCESS_KEY}}
            AWS_SECRET_ACCESS_KEY=${{env.SECRET_ACCESS_KEY}}
            COMMAND=gmail-api

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/appliscan-gmail-api/${{ env.EMAIL_SERVICE }}:latest
          service: ${{ env.EMAIL_SERVICE }}
          region: us-central1
          platform: managed
          allow-unauthenticated: true